using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AICopilot.EntityFrameworkCore.Migrations.RagDbContext
{
    public partial class InitialRagSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(name: "rag");

            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF to_regclass('rag.embedding_models') IS NULL
                       AND to_regclass('rag.knowledge_bases') IS NULL
                       AND to_regclass('rag.documents') IS NULL
                       AND to_regclass('rag.document_chunks') IS NULL THEN
                        IF to_regclass('public.embedding_models') IS NOT NULL
                           OR to_regclass('public.knowledge_bases') IS NOT NULL
                           OR to_regclass('public.documents') IS NOT NULL
                           OR to_regclass('public.document_chunks') IS NOT NULL THEN
                            IF to_regclass('public.embedding_models') IS NOT NULL THEN
                                ALTER TABLE public.embedding_models SET SCHEMA rag;
                            END IF;

                            IF to_regclass('public.knowledge_bases') IS NOT NULL THEN
                                ALTER TABLE public.knowledge_bases SET SCHEMA rag;
                            END IF;

                            IF to_regclass('public.documents') IS NOT NULL THEN
                                ALTER TABLE public.documents SET SCHEMA rag;
                            END IF;

                            IF to_regclass('public.document_chunks') IS NOT NULL THEN
                                ALTER TABLE public.document_chunks SET SCHEMA rag;
                            END IF;
                        ELSE
                            CREATE TABLE rag.embedding_models (
                                id uuid NOT NULL,
                                name character varying(100) NOT NULL,
                                provider character varying(50) NOT NULL,
                                base_url character varying(500) NOT NULL,
                                api_key character varying(2048) NULL,
                                model_name character varying(100) NOT NULL,
                                dimensions integer NOT NULL,
                                max_tokens integer NOT NULL,
                                is_enabled boolean NOT NULL,
                                CONSTRAINT "PK_embedding_models" PRIMARY KEY (id)
                            );

                            CREATE UNIQUE INDEX "IX_embedding_models_name"
                                ON rag.embedding_models (name);

                            CREATE TABLE rag.knowledge_bases (
                                id uuid NOT NULL,
                                name character varying(200) NOT NULL,
                                description character varying(1000) NOT NULL,
                                embedding_model_id uuid NOT NULL,
                                CONSTRAINT "PK_knowledge_bases" PRIMARY KEY (id)
                            );

                            CREATE TABLE rag.documents (
                                id integer GENERATED BY DEFAULT AS IDENTITY,
                                knowledge_base_id uuid NOT NULL,
                                name character varying(256) NOT NULL,
                                file_path character varying(500) NOT NULL,
                                extension character varying(50) NOT NULL,
                                file_hash character varying(64) NOT NULL,
                                status character varying(50) NOT NULL,
                                chunk_count integer NOT NULL,
                                error_message text NULL,
                                created_at timestamp with time zone NOT NULL,
                                processed_at timestamp with time zone NULL,
                                CONSTRAINT "PK_documents" PRIMARY KEY (id),
                                CONSTRAINT "FK_documents_knowledge_bases_knowledge_base_id"
                                    FOREIGN KEY (knowledge_base_id)
                                    REFERENCES rag.knowledge_bases (id)
                                    ON DELETE CASCADE
                            );

                            CREATE INDEX "IX_documents_knowledge_base_id"
                                ON rag.documents (knowledge_base_id);

                            CREATE TABLE rag.document_chunks (
                                id integer GENERATED BY DEFAULT AS IDENTITY,
                                document_id integer NOT NULL,
                                index integer NOT NULL,
                                content text NOT NULL,
                                vector_id character varying(100) NULL,
                                created_at timestamp with time zone NOT NULL,
                                CONSTRAINT "PK_document_chunks" PRIMARY KEY (id),
                                CONSTRAINT "FK_document_chunks_documents_document_id"
                                    FOREIGN KEY (document_id)
                                    REFERENCES rag.documents (id)
                                    ON DELETE CASCADE
                            );

                            CREATE UNIQUE INDEX "IX_document_chunks_document_id_index"
                                ON rag.document_chunks (document_id, index);
                        END IF;
                    END IF;
                END $$;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF to_regclass('rag.document_chunks') IS NOT NULL
                       AND to_regclass('public.document_chunks') IS NULL THEN
                        ALTER TABLE rag.document_chunks SET SCHEMA public;
                    END IF;

                    IF to_regclass('rag.documents') IS NOT NULL
                       AND to_regclass('public.documents') IS NULL THEN
                        ALTER TABLE rag.documents SET SCHEMA public;
                    END IF;

                    IF to_regclass('rag.knowledge_bases') IS NOT NULL
                       AND to_regclass('public.knowledge_bases') IS NULL THEN
                        ALTER TABLE rag.knowledge_bases SET SCHEMA public;
                    END IF;

                    IF to_regclass('rag.embedding_models') IS NOT NULL
                       AND to_regclass('public.embedding_models') IS NULL THEN
                        ALTER TABLE rag.embedding_models SET SCHEMA public;
                    END IF;
                END $$;
                """);
        }
    }
}
