namespace AICopilot.Core.AiGateway.Aggregates.LanguageModel;

public record ModelParameters
{
    /// <summary>
    /// Total context window available to the model.
    /// </summary>
    public int MaxTokens { get; init; }

    /// <summary>
    /// Default maximum tokens generated by the model.
    /// </summary>
    public int MaxOutputTokens { get; init; } = 1024;

    public float Temperature { get; init; } = 0.7f;
}
