using System.Text.Json;
using System.Text.RegularExpressions;
using AICopilot.AiGatewayService.Agents;
using AICopilot.Services.Contracts;
using AICopilot.SharedKernel.Ai;
using Microsoft.Extensions.Options;

namespace AICopilot.AiGatewayService.Workflows.Executors;

internal sealed partial class CloudReadOnlyLlmTextToSqlGenerator(
    ConfiguredAgentRuntimeFactory agentFactory,
    IOptions<CloudReadOnlyTextToSqlOptions>? options = null) : ICloudReadOnlyTextToSqlGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = false
    };

    public async Task<CloudReadOnlyTextToSqlGenerationResult> GenerateAsync(
        CloudReadOnlyTextToSqlGenerationRequest request,
        CancellationToken cancellationToken = default)
    {
        var resolvedOptions = options?.Value ?? new CloudReadOnlyTextToSqlOptions();
        if (!resolvedOptions.Enabled)
        {
            return CloudReadOnlyTextToSqlGenerationResult.Failure(
                "Cloud readonly Text-to-SQL generator is disabled.");
        }

        try
        {
            await using var scopedAgent = await agentFactory.CreateAgentAsync(
                resolvedOptions.TemplateName,
                instructions => instructions,
                chatOptions =>
                {
                    chatOptions.Temperature = 0;
                    chatOptions.MaxOutputTokens = resolvedOptions.ResolveMaxOutputTokens();
                    chatOptions.Tools = [];
                });

            var session = await scopedAgent.Agent.CreateSessionAsync(cancellationToken);
            var payload = JsonSerializer.Serialize(BuildInput(request), JsonOptions);
            var response = await scopedAgent.Agent.RunStructuredAsync<CloudReadOnlyTextToSqlModelResponse>(
                [new AiChatMessage(AiChatRole.User, payload)],
                session,
                JsonOptions,
                new RuntimeAgentRunOptions(new AiChatOptions
                {
                    Temperature = 0,
                    MaxOutputTokens = resolvedOptions.ResolveMaxOutputTokens(),
                    Tools = []
                }),
                cancellationToken);

            return BuildResult(response.Result);
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception)
        {
            return CloudReadOnlyTextToSqlGenerationResult.Failure(
                "Cloud readonly Text-to-SQL model is unavailable.");
        }
    }

    private static CloudReadOnlyTextToSqlGenerationResult BuildResult(
        CloudReadOnlyTextToSqlModelResponse? response)
    {
        if (response is null)
        {
            return CloudReadOnlyTextToSqlGenerationResult.Failure(
                "Cloud readonly Text-to-SQL model did not return a structured response.");
        }

        if (!response.IsSuccess)
        {
            return CloudReadOnlyTextToSqlGenerationResult.Failure(
                string.IsNullOrWhiteSpace(response.FailureReason)
                    ? "Cloud readonly Text-to-SQL model could not generate a governed query."
                    : response.FailureReason.Trim());
        }

        var sql = StripCodeFence(response.Sql);
        if (string.IsNullOrWhiteSpace(sql))
        {
            return CloudReadOnlyTextToSqlGenerationResult.Failure(
                "Cloud readonly Text-to-SQL model returned an empty SQL statement.");
        }

        var parameters = NormalizeParameters(response.Parameters, out var parameterError);
        if (parameterError is not null)
        {
            return CloudReadOnlyTextToSqlGenerationResult.Failure(parameterError);
        }

        return CloudReadOnlyTextToSqlGenerationResult.Success(
            sql,
            string.IsNullOrWhiteSpace(response.Explanation) ? "Generated by Cloud readonly Text-to-SQL model." : response.Explanation.Trim(),
            parameters,
            response.Warnings?.Where(warning => !string.IsNullOrWhiteSpace(warning)).Select(warning => warning.Trim()).ToArray());
    }

    private static object BuildInput(CloudReadOnlyTextToSqlGenerationRequest request)
    {
        return new
        {
            task = "cloud-readonly-text-to-sql",
            question = request.Question,
            limit = request.Limit,
            previousSqlForRepair = request.PreviousSqlForRepair,
            governedSchema = request.AllowedTables
                .OrderBy(table => table, StringComparer.OrdinalIgnoreCase)
                .Select(table =>
                {
                    var orderedColumns = request.AllowedColumns.TryGetValue(table, out var columns)
                        ? columns.OrderBy(column => column, StringComparer.OrdinalIgnoreCase).ToArray()
                        : [];

                    return new
                    {
                        table,
                        columns = orderedColumns,
                        columnTypes = orderedColumns
                            .Select(column => new
                            {
                                column,
                                type = CloudReadOnlyGovernedSchema.AllowedColumnTypes.TryGetValue(table, out var tableColumnTypes)
                                       && tableColumnTypes.TryGetValue(column, out var columnType)
                                    ? columnType
                                    : null
                            })
                            .Where(entry => entry.type is not null)
                            .ToArray()
                    };
                })
                .ToArray(),
            joinHints = CloudReadOnlyGovernedSchema.JoinHints
                .Where(hint => request.AllowedTables.Contains(hint.LeftTable) &&
                               request.AllowedTables.Contains(hint.RightTable) &&
                               request.AllowedColumns.TryGetValue(hint.LeftTable, out var leftColumns) &&
                               leftColumns.Contains(hint.LeftColumn) &&
                               request.AllowedColumns.TryGetValue(hint.RightTable, out var rightColumns) &&
                               rightColumns.Contains(hint.RightColumn))
                .Select(hint => new
                {
                    left = $"{hint.LeftTable}.{hint.LeftColumn}",
                    right = $"{hint.RightTable}.{hint.RightColumn}"
                })
                .ToArray(),
            repairHistory = request.RepairHistory.Select(attempt => new
            {
                attempt.AttemptIndex,
                stage = attempt.Stage.ToString(),
                failureCode = attempt.FailureCode.ToString(),
                attempt.CanRepairSql,
                attempt.CanRetry,
                attempt.SqlHash,
                attempt.SqlLength,
                attempt.SafeErrorSummary
            }).ToArray(),
            outputContract = new
            {
                isSuccess = "true only when a governed readonly SELECT is produced",
                sql = "single PostgreSQL SELECT statement without semicolon; use @parameter_name for literal filter values",
                parameters = "object mapping parameter names to scalar values; omit or empty object when none",
                explanation = "one short technical sentence",
                warnings = "array of short warning strings",
                failureReason = "short safe reason when isSuccess is false"
            }
        };
    }

    private static IReadOnlyDictionary<string, object?> NormalizeParameters(
        IReadOnlyDictionary<string, JsonElement>? parameters,
        out string? error)
    {
        error = null;
        var normalized = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
        if (parameters is null)
        {
            return normalized;
        }

        foreach (var (name, value) in parameters)
        {
            if (!ParameterNameRegex().IsMatch(name))
            {
                error = $"Parameter name '{name}' is not allowed.";
                return normalized;
            }

            if (!TryConvertParameterValue(value, out var converted))
            {
                error = $"Parameter '{name}' must be a scalar JSON value.";
                return normalized;
            }

            normalized[name] = converted;
        }

        return normalized;
    }

    private static bool TryConvertParameterValue(JsonElement value, out object? converted)
    {
        converted = null;
        switch (value.ValueKind)
        {
            case JsonValueKind.Null:
            case JsonValueKind.Undefined:
                return true;
            case JsonValueKind.String:
                converted = value.GetString();
                return true;
            case JsonValueKind.True:
            case JsonValueKind.False:
                converted = value.GetBoolean();
                return true;
            case JsonValueKind.Number:
                if (value.TryGetInt64(out var longValue))
                {
                    converted = longValue;
                    return true;
                }

                if (value.TryGetDouble(out var doubleValue))
                {
                    converted = doubleValue;
                    return true;
                }

                return false;
            default:
                return false;
        }
    }

    private static string? StripCodeFence(string? sql)
    {
        if (string.IsNullOrWhiteSpace(sql))
        {
            return null;
        }

        var trimmed = sql.Trim();
        if (!trimmed.StartsWith("```", StringComparison.Ordinal))
        {
            return trimmed;
        }

        return CodeFenceRegex()
            .Replace(trimmed, "$1")
            .Trim();
    }

    [GeneratedRegex(@"^```(?:sql)?\s*(.*?)\s*```$", RegexOptions.Singleline | RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex CodeFenceRegex();

    [GeneratedRegex(@"^[a-z_][a-z0-9_]*$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ParameterNameRegex();
}

internal sealed record CloudReadOnlyTextToSqlModelResponse
{
    public bool IsSuccess { get; init; }

    public string? Sql { get; init; }

    public Dictionary<string, JsonElement>? Parameters { get; init; }

    public string? Explanation { get; init; }

    public string[]? Warnings { get; init; }

    public string? FailureReason { get; init; }
}
