// <auto-generated />
using System;
using AICopilot.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AICopilot.EntityFrameworkCore.Migrations.AiGatewayDbContext
{
    [DbContext(typeof(global::AICopilot.EntityFrameworkCore.AiGatewayDbContext))]
    [Migration("20260428145951_InitialAiGatewaySchema")]
    partial class InitialAiGatewaySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aigateway")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.ApprovalPolicy.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresOnsiteAttestation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_onsite_attestation");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_name");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.PrimitiveCollection<string[]>("ToolNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tool_names");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("approval_policies", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.ConversationTemplate.ConversationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("conversation_templates", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.LanguageModel.LanguageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Name")
                        .IsUnique();

                    b.ToTable("language_models", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("messages", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("OnsiteConfirmationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onsite_confirmation_expires_at");

                    b.Property<DateTimeOffset?>("OnsiteConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onsite_confirmed_at");

                    b.Property<string>("OnsiteConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("onsite_confirmed_by");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", "aigateway");
                });

            modelBuilder.Entity("AICopilot.EntityFrameworkCore.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_on_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("event_type");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type_name");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("outbox_messages", "outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.ConversationTemplate.ConversationTemplate", b =>
                {
                    b.OwnsOne("AICopilot.Core.AiGateway.Aggregates.ConversationTemplate.TemplateSpecification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("ConversationTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxTokens")
                                .HasColumnType("integer")
                                .HasColumnName("max_tokens");

                            b1.Property<float?>("Temperature")
                                .HasColumnType("real")
                                .HasColumnName("temperature");

                            b1.HasKey("ConversationTemplateId");

                            b1.ToTable("conversation_templates", "aigateway");

                            b1.WithOwner()
                                .HasForeignKey("ConversationTemplateId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.LanguageModel.LanguageModel", b =>
                {
                    b.OwnsOne("AICopilot.Core.AiGateway.Aggregates.LanguageModel.ModelParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("LanguageModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxTokens")
                                .HasColumnType("integer")
                                .HasColumnName("max_tokens");

                            b1.Property<float>("Temperature")
                                .HasColumnType("real")
                                .HasColumnName("temperature");

                            b1.HasKey("LanguageModelId");

                            b1.ToTable("language_models", "aigateway");

                            b1.WithOwner()
                                .HasForeignKey("LanguageModelId");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Message", b =>
                {
                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Sessions.Session", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Session", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
