// <auto-generated />
using System;
using AICopilot.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AICopilot.EntityFrameworkCore.Migrations.AiGatewayDbContext
{
    [DbContext(typeof(global::AICopilot.EntityFrameworkCore.AiGatewayDbContext))]
    partial class AiGatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aigateway")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputJson")
                        .HasColumnType("text")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text")
                        .HasColumnName("output_json");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("step_index");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("step_type");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("ToolCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_code");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "StepIndex")
                        .IsUnique();

                    b.ToTable("agent_steps", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveRunAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_run_attempt_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FinalSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("final_summary");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("goal");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_json");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_level");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("RunAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("run_attempt_count");

                    b.Property<DateTimeOffset?>("RunLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_lease_expires_at");

                    b.Property<Guid?>("RunLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_lease_id");

                    b.Property<string>("RunLeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("run_lease_owner");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("status");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("task_code");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("task_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_agent_tasks_user_id");

                    b.ToTable("agent_tasks", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentTaskRunAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_no");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("failure_code");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SafeMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("safe_message");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_agent_task_run_attempts_task_id");

                    b.HasIndex("TaskId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_task_run_attempts_task_attempt_no");

                    b.ToTable("agent_task_run_attempts", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentTaskRunQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("failure_code");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("RunAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_attempt_id");

                    b.Property<string>("SafeMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("safe_message");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeaseExpiresAt")
                        .HasDatabaseName("ix_agent_task_run_queue_items_lease_expires_at");

                    b.HasIndex("RunAttemptId")
                        .HasDatabaseName("ix_agent_task_run_queue_items_run_attempt_id");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_task_run_queue_items_active_task")
                        .HasFilter("status IN ('Queued', 'Leased')");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_agent_task_run_queue_items_status_available_at");

                    b.ToTable("agent_task_run_queue_items", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentWorkerHeartbeat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveQueueItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_queue_item_id");

                    b.Property<Guid?>("ActiveTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_task_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("version");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("worker_id");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("worker_name");

                    b.Property<string>("WorkspaceRootHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("workspace_root_hash");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTaskId")
                        .HasDatabaseName("ix_agent_worker_heartbeats_active_task_id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_agent_worker_heartbeats_last_seen_at");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_worker_heartbeats_worker_id");

                    b.ToTable("agent_worker_heartbeats", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.ApprovalPolicy.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresOnsiteAttestation")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_onsite_attestation");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_name");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.PrimitiveCollection<string[]>("ToolNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tool_names");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("approval_policies", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Approvals.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("approval_comment");

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("approval_type");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_approval_requests_task_id");

                    b.ToTable("approval_requests", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Artifacts.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("artifact_type");

                    b.Property<string>("Boundary")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("boundary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_step_id");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<bool>("IsSandbox")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sandbox");

                    b.Property<bool>("IsSimulation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_simulation");

                    b.Property<bool>("IsTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_truncated");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("QueryHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("query_hash");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("relative_path");

                    b.Property<string>("ResultHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("result_hash");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("SourceLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_label");

                    b.Property<string>("SourceMode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_mode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "RelativePath");

                    b.ToTable("artifacts", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Artifacts.ArtifactWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("root_path");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkspaceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workspace_code");

                    b.Property<string>("WorkspaceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("workspace_url");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.HasIndex("WorkspaceCode")
                        .IsUnique();

                    b.ToTable("artifact_workspaces", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.ConversationTemplate.ConversationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BuiltInVersion")
                        .HasColumnType("integer")
                        .HasColumnName("built_in_version");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("conversation_templates", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.LanguageModel.LanguageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset?>("ConnectivityCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connectivity_checked_at");

                    b.Property<string>("ConnectivityError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("connectivity_error");

                    b.Property<int>("ConnectivityStatus")
                        .HasColumnType("integer")
                        .HasColumnName("connectivity_status");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("protocol_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Usage")
                        .HasColumnType("integer")
                        .HasColumnName("usage");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Name")
                        .IsUnique();

                    b.ToTable("language_models", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.RoutingModel.RoutingModelConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasFilter("is_active");

                    b.HasIndex("ModelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("routing_model_configurations", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.RuntimeSettings.ChatRuntimeSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgentPlanningHistoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("agent_planning_history_count");

                    b.Property<int>("AnswerHistoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("answer_history_count");

                    b.Property<int>("ContextTokenLimit")
                        .HasColumnType("integer")
                        .HasColumnName("context_token_limit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RagRewriteHistoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("rag_rewrite_history_count");

                    b.Property<int>("RoutingHistoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("routing_history_count");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("chat_runtime_settings", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("ContextWindowTokens")
                        .HasColumnType("integer")
                        .HasColumnName("context_window_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FinalModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("final_model_id");

                    b.Property<string>("FinalModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("final_model_name");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_output_tokens");

                    b.Property<string>("RenderPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("render_payload_json");

                    b.Property<Guid?>("RoutingModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("routing_model_id");

                    b.Property<string>("RoutingModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("routing_model_name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_messages_session_id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_session_id_sequence");

                    b.ToTable("messages", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.MessageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_step_id");

                    b.Property<Guid?>("AgentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_task_id");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_request_id");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<Guid?>("ArtifactWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_workspace_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentTaskId")
                        .HasDatabaseName("ix_message_events_agent_task_id");

                    b.HasIndex("ApprovalRequestId")
                        .HasDatabaseName("ix_message_events_approval_request_id");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_message_events_artifact_id");

                    b.HasIndex("ArtifactWorkspaceId")
                        .HasDatabaseName("ix_message_events_artifact_workspace_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_events_message_id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_message_events_session_id_sequence");

                    b.ToTable("message_events", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("LastMessageSummary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_message_summary");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("message_count");

                    b.Property<DateTimeOffset?>("OnsiteConfirmationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onsite_confirmation_expires_at");

                    b.Property<DateTimeOffset?>("OnsiteConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onsite_confirmed_at");

                    b.Property<string>("OnsiteConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("onsite_confirmed_by");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Skills.SkillDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedDataSourceModes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_data_source_modes");

                    b.PrimitiveCollection<string[]>("AllowedKnowledgeScopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_knowledge_scopes");

                    b.PrimitiveCollection<string[]>("AllowedToolCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_tool_codes");

                    b.Property<string>("ApprovalPolicy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("approval_policy");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.PrimitiveCollection<string[]>("OutputComponentTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("output_component_types");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_level");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("skill_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SkillCode")
                        .IsUnique();

                    b.ToTable("skill_definitions", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Tools.ToolExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("artifact_id");

                    b.Property<string>("AuditMetadata")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("audit_metadata");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("InputSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("input_summary");

                    b.Property<string>("OutputSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("output_summary");

                    b.Property<Guid?>("RunAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_attempt_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("tool_code");

                    b.HasKey("Id");

                    b.HasIndex("RunAttemptId")
                        .HasDatabaseName("ix_tool_execution_records_run_attempt_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_tool_execution_records_task_id");

                    b.HasIndex("ToolCode")
                        .HasDatabaseName("ix_tool_execution_records_tool_code");

                    b.HasIndex("TaskId", "StepId")
                        .HasDatabaseName("ix_tool_execution_records_task_step");

                    b.ToTable("tool_execution_records", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Tools.ToolRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalPolicy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("approval_policy");

                    b.Property<string>("AuditLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("audit_level");

                    b.PrimitiveCollection<string[]>("BusinessDomains")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("business_domains");

                    b.Property<int>("CatalogVersion")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_version");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataBoundary")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("data_boundary");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("InputSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_schema_json");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsExecutableByAgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_executable_by_agent");

                    b.Property<bool>("IsVisibleToPlanner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible_to_planner");

                    b.Property<string>("OutputSchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_schema_json");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider_type");

                    b.Property<string>("RequiredPermission")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("required_permission");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_level");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_name");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_type");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("tool_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ToolCode")
                        .IsUnique();

                    b.ToTable("tool_registrations", "aigateway");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Uploads.UploadRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_task_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid?>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<int?>("RagDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("rag_document_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseId")
                        .HasDatabaseName("ix_upload_records_knowledge_base_id");

                    b.HasIndex("UserId", "AgentTaskId")
                        .HasDatabaseName("ix_upload_records_user_agent_task");

                    b.HasIndex("UserId", "SessionId")
                        .HasDatabaseName("ix_upload_records_user_session");

                    b.ToTable("upload_records", "aigateway");
                });

            modelBuilder.Entity("AICopilot.EntityFrameworkCore.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_on_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("event_type");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type_name");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "DeadLetteredOnUtc", "NextAttemptUtc");

                    b.ToTable("outbox_messages", "outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentStep", b =>
                {
                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentTask", null)
                        .WithMany("Steps")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Artifacts.Artifact", b =>
                {
                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Artifacts.ArtifactWorkspace", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.ConversationTemplate.ConversationTemplate", b =>
                {
                    b.OwnsOne("AICopilot.Core.AiGateway.Aggregates.ConversationTemplate.TemplateSpecification", "Specification", b1 =>
                        {
                            b1.Property<Guid>("ConversationTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxTokens")
                                .HasColumnType("integer")
                                .HasColumnName("max_tokens");

                            b1.Property<float?>("Temperature")
                                .HasColumnType("real")
                                .HasColumnName("temperature");

                            b1.HasKey("ConversationTemplateId");

                            b1.ToTable("conversation_templates", "aigateway");

                            b1.WithOwner()
                                .HasForeignKey("ConversationTemplateId");
                        });

                    b.Navigation("Specification")
                        .IsRequired();
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.LanguageModel.LanguageModel", b =>
                {
                    b.OwnsOne("AICopilot.Core.AiGateway.Aggregates.LanguageModel.ModelParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("LanguageModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxOutputTokens")
                                .HasColumnType("integer")
                                .HasColumnName("max_output_tokens");

                            b1.Property<int>("MaxTokens")
                                .HasColumnType("integer")
                                .HasColumnName("max_tokens");

                            b1.Property<float>("Temperature")
                                .HasColumnType("real")
                                .HasColumnName("temperature");

                            b1.HasKey("LanguageModelId");

                            b1.ToTable("language_models", "aigateway");

                            b1.WithOwner()
                                .HasForeignKey("LanguageModelId");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Message", b =>
                {
                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Sessions.Session", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.MessageEvent", b =>
                {
                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("AgentTaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_message_events_agent_tasks_agent_task_id");

                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Approvals.ApprovalRequest", null)
                        .WithMany()
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_message_events_approval_requests_approval_request_id");

                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Artifacts.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_message_events_artifacts_artifact_id");

                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Artifacts.ArtifactWorkspace", null)
                        .WithMany()
                        .HasForeignKey("ArtifactWorkspaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_message_events_artifact_workspaces_artifact_workspace_id");

                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Sessions.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_message_events_messages_message_id");

                    b.HasOne("AICopilot.Core.AiGateway.Aggregates.Sessions.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_events_sessions_session_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.AgentTasks.AgentTask", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Artifacts.ArtifactWorkspace", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("AICopilot.Core.AiGateway.Aggregates.Sessions.Session", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
